[build]
  # Use Node.js v20 for builds (fixes npm install issues)
  node_version = "20"

  # Functions live here
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  # Your environment variables
  AUTH0_DOMAIN = ""
  AUTH0_CLIENT_ID = ""
  AUTH0_AUDIENCE = ""
  GHL_TOKEN = ""
  GHL_LAST_USAGE_FIELD_ID = ""
  ALLOWED_ORIGINS = "animated-entremet-6d0e30.netlify.app"

  [functions]
  node_bundler = "esbuild"
